version: '2'
services:
    inventory-app:
        image: inventory
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://inventory-mariadb:3306/inventory
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    inventory-mariadb:
        extends:
            file: mariadb.yml
            service: inventory-mariadb
